### ISSUE TITLE
removal(method="CarleStrub") estimates do not default to total catch when catches are higher on 2nd or 3rd pass

### ISSUE THREAD

**Issue by pennockc** [fishR-Core-Team/FSA#93]
Perhaps I'm mistaken, but I thought the Carle-Strub method overcame the deficiency of the Zippin method when catches were higher in subsequent passes by defaulting estimates to the total catch?

Currently for these scenarios, removal() is giving an estimate with confidence intervals that overlap zero. The same happens if the 2nd pass is higher than the 1st or 3rd.

d<-c(100,75,240)
dest<-removal(d, just.ests=TRUE)
dest

           No         No.se        No.LCI        No.UCI             p          p.se 
 1.977600e+04  1.670139e+05 -3.075652e+05  3.471172e+05  7.027585e-03  5.976998e-02 
        p.LCI         p.UCI 
-1.101194e-01  1.241746e-01 

No = 19776, but should = 415.

**Comment by jcdoll79** [comment]
Hi, 

Are you using simulated data to know that all fish were removed and thus N0 = 415?

You are correct that the Carle-Strub method does overcome the problem with higher catches in subsequent passes, however, it relies on a Bayesian approach to weight the likelihood. This approach uses a prior probability distribution (beta distribution) on p. In other words, the analysis incorporates prior information about p obtained through other studies or the literature. The prior information needs to be defined as a beta distribution that represents the prior belief about p before you collected data. 

If there is reason to believe p is very high, which would need to be if 240 were removed on the last pass and all remaining fish were removed, then the distribution of p could be defined with beta(alpha=1000,beta=1). Although this is a bit of an extreme example. This beta distribution can be visualized by:

`hist(rbeta(n=1000,shape1=1000,shape2=1))`

To incorporate this prior in FSA

`summary(removal(d,alpha=1000,beta=1),just.ests=TRUE)`

I should emphasize that selection of the prior probability distribution must be supported with data, either from another study or the literature.

The default prior in FSA is alpha=1 and beta=1, which is a flat prior between 0 and 1 for p. This tells FSA that there is no prior information about p.

With all that said, it might be difficult to get reasonable estimates in your case since the last pass is more than twice the first. I ran into a similar situation during a smallmouth bass deletion study in a moderate sized river. I ended up using the N-mixture model (Royle 2004) with parameters estimated using Bayesian inference. You can also fit the Royle (2004) model using the R package 'unmarked" and the gmultmix function.

https://www.raco.cat/index.php/abc/article/view/57295

Jason

**Comment by pennockc** [comment]
Ok, thanks for the detailed explanation. I'm working with empirical removal data, and in this particular instance, I'm running into issues getting reliable estimates in some years for a benthic-species (sculpin).

I'll probably give the unmarked models a go.

Thanks,

Casey

**Comment by jcdoll79** [comment]
Hi Casey,

One of my dissertation chapters used depletion methods on several stream in Indiana. Detection was very low for all benthic species (e.g., Mottled sculpin and darters), which often lead to increasing catch rates after successive passes. I fit the Royle model in JAGS and was primarily interested in family level coefficients in a hierarchical model. At any rate, I do remember benthic species being hard to capture with a consistent depletion. I also wasn't using a seine to catch benthic species as they were swept downstream but a seine would have likely improved detection. 

I think the unmarked package should be able to help you out for the species you're having trouble with. The Royle (2004) will also work with species where you do have a consistent depletion across passes.

Good luck,
Jason
